version: "3"

services:
  epadel-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: QWElkj132!
      MSSQL_PID: Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - epadelnet

  epadel-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=epadel-db,1433;Database=ePadel;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5192:5192
    networks:
      - epadelnet
    links:
      - epadel-db
    depends_on:
      - epadel-db

networks:
  epadelnet:
    driver: bridge